name: Release X-ui
on:
  push:
    tags:
      - 0.*
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用自动提供的 token
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: ${{ github.ref }}
      #     draft: true
      #     prerelease: true

      - name: Delete existing files
        run: |
          rm -f bin/*  # 删除可能存在的文件
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          mkdir -p bin
          git commit -am "Delete existing files"
          git pull origin main

  linuxamd64build:
    name: Build x-ui AMD64 version
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Build Linux AMD64 Version
        run: |
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o xui-release -v main.go
          mkdir x-ui
          cp xui-release x-ui/xui-release
          cp x-ui.service x-ui/x-ui.service
          cp x-ui.sh x-ui/x-ui.sh
          cd x-ui
          mv xui-release x-ui
          mkdir bin
          cd bin
          # curl -s https://api.github.com/repos/XTLS/Xray-core/releases/latest \
          #     | grep "browser_download_url.*Xray-linux-64.zip" \
          #     | cut -d '"' -f 4 \
          #     | xargs curl -L -o xray.zip && \
          curl -s https://api.github.com/repos/XTLS/Xray-core/releases/latest | grep "browser_download_url.*Xray-linux-64.zip" | cut -d '"' -f 4 | xargs curl -L -o xray.zip
          unzip  xray.zip
          rm -f xray.zip geoip.dat geosite.dat
          # 下载 geoip.dat 和 geosite.dat
          curl -s https://api.github.com/repos/Loyalsoldier/v2ray-rules-dat/releases/latest | grep "browser_download_url.*geoip.dat" | cut -d '"' -f 4 | xargs curl -L -o geoip.dat
          curl -s https://api.github.com/repos/Loyalsoldier/v2ray-rules-dat/releases/latest | grep "browser_download_url.*geosite.dat" | cut -d '"' -f 4 | xargs curl -L -o geosite.dat
          mv xray xray-linux-amd64
          cd ../..
          tree 
          tar -zcvf x-ui-linux-amd64.tar.gz x-ui

      - name: Commit changes
        run: |
          export TZ="Asia/Shanghai"
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          tree 
          pwd
          rm -f xui-release
          cp -f x-ui/bin/xray-linux-amd64 bin/
          cp -f x-ui/bin/geoip.dat bin/
          cp -f x-ui/bin/geosite.dat bin/
          git add -f bin/xray-linux-amd64
          git add -f bin/geoip.dat
          git add -f bin/geosite.dat
          git commit -m "$TIMESTAMP"
          git pull origin main
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
             x-ui-linux-amd64.tar.gz
          tag_name: latest

  linuxarm64build:
    name: Build x-ui ARM64 version
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Build Linux ARM64 Version
        run: |
          sudo apt-get update
          sudo apt install gcc-aarch64-linux-gnu
          CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc go build -o xui-release -v main.go
          mkdir x-ui
          cp xui-release x-ui/xui-release
          cp x-ui.service x-ui/x-ui.service
          cp x-ui.sh x-ui/x-ui.sh
          cd x-ui
          mv xui-release x-ui
          mkdir bin
          cd bin
          wget https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-arm64-v8a.zip
          unzip -o Xray-linux-arm64-v8a.zip && rm -f Xray-linux-arm64-v8a.zip geoip.dat geosite.dat
          wget https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
          wget https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
          mv xray xray-linux-arm64
          cd ../..
          tar -zcvf x-ui-linux-arm64.tar.gz x-ui

      - name: Commit changes
        run: |
          export TZ="Asia/Shanghai"
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          cp -f x-ui/bin/xray-linux-arm64 bin/
          git add -f bin/xray-linux-arm64
          git commit -m "$TIMESTAMP"
          git pull origin main
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
             x-ui-linux-arm64.tar.gz
          tag_name: latest

  linuxs390xbuild:
    name: Build x-ui S390X version
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Build Linux S390X Version
        run: |
          sudo apt-get update
          sudo apt install gcc-s390x-linux-gnu -y
          CGO_ENABLED=1 GOOS=linux GOARCH=s390x CC=s390x-linux-gnu-gcc go build -o xui-release -v main.go
          mkdir x-ui
          cp xui-release x-ui/xui-release
          cp x-ui.service x-ui/x-ui.service
          cp x-ui.sh x-ui/x-ui.sh
          cd x-ui
          mv xui-release x-ui
          mkdir bin
          cd bin
          wget https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-s390x.zip
          unzip -o Xray-linux-s390x.zip && rm -f Xray-linux-s390x.zip geoip.dat geosite.dat
          wget https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
          wget https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
          mv xray xray-linux-s390x
          cd ../..
          tar -zcvf x-ui-linux-s390x.tar.gz x-ui

      - name: Commit changes
        run: |
          export TZ="Asia/Shanghai"
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          cp -f x-ui/bin/xray-linux-s390x bin/
          git add -f bin/xray-linux-s390x
          git commit -m "$TIMESTAMP"
          git pull origin main
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
             x-ui-linux-s390x.tar.gz
          tag_name: latest

