name: Update Go Modules

on:
  workflow_dispatch:

jobs:
  update-modules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'  # 指定你的 Go 版本

    - name: Clean Go module cache
      run: go clean -modcache  # 清理模块缓存
      
    - name: Remove go.sum
      run: |
        if [ -f go.sum ]; then
          rm go.sum  # 删除现有的 go.sum 文件
        fi

    - name: Install dependencies
      run: |
        go mod tidy
    #     go mod download

    # - name: Update go.mod and regenerate go.sum
    #   run: |
    #     go get -u ./...  # 更新所有依赖
    #     go mod tidy      # 重新整理依赖

    - name: Commit changes
      run: |
        export TZ="Asia/Shanghai"
        TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add go.mod go.sum
        git commit -m "$TIMESTAMP"
        git push


